### ISSUE TITLE
Greek alphabet strings in attribute titles are mangled when truncated due to substr()

### ISSUE THREAD

**Issue by arius28** [bramley/phplist-plugin-common#16]
Hey @bramley,

I just posted a [pull request](https://github.com/phpList/phplist3/pull/876) on a similar issue in the phplist3 repo but I also see the same problem with Greek characters in advanced search of the Subscribers plugin. Attributes in the Greek alphabet are getting mangled when the system thinks it should truncate the attribute title. 

I located the truncating code in https://github.com/bramley/phplist-plugin-common/blob/736cf14dc40da0db7d79d59df3df8341f21b901c/plugins/Common/DAO/AttributeTrait.php#L75-L79

Maybe doing a check if the mb_ equivalent functions are present and if so using those would be sufficient. Something along the lines phplist core does in [lib.php](https://github.com/phpList/phplist3/blob/cc9a351a5f175635414796f8beca1da1624350af/public_html/lists/admin/lib.php#L1935-L1940).
#

Screenshot of how it looks like currently:

![subscribers_screen1](https://user-images.githubusercontent.com/12183504/176673388-7604168d-00e2-46c7-83e8-14b010bbd7f4.jpg)

**Comment by arius28** [comment]
Here are the three attribute names which appear corrupted in the phpList installation I took the screenshot from.

ΒΑΣΙΚΗ ΓΛΩΣΣΑ
Δ/Γ ΓΕΡΜΑΝΙΚΑ
Δ/Γ ΙΣΠΑΝΙΚΑ

**Comment by bramley** [comment]
Looking more closely at `shortenTextDisplay()`, it is not really suitable for populating a select list because it returns an html `span` element, not just the shortened text. The `span` element is ok when displaying attribute names on a page but not otherwise. I am looking at a change to `shortenTextDisplay()` to split out the actual shortening into a separate function which can be used by this plugin and also by your proposed change to users.php.

**Comment by bramley** [comment]
I don't know when the proposed change to core phplist will be merged and released, so have copied the `shortenText` function into this plugin and now use that to shorted attribute names.
I can change to use the core phplist function when it has been released.
